#!/bin/bash

# Import Library
. lib/logMod/logMod

# Supported Program Modes
NOT_INITIALIZED_MODE="-1"
INFO_MODE="0"
NORMAL_MODE="1"
SOURCE_MODE="2"
TARGET_MODE="4"


PGM_MODE="$NOT_INITIALIZED_MODE"
NON_FLAG_CNT=2
PGM_SETBY=""
PARM_CNT="$#"
VERSION=1.5.0
MAINTAINER="David Obernöder"
ONLY_SINGLE_IMAGES=0
ONLY_PULL_SPLIT=0
SOURCE_IMAGE=""
TARGET_IMAGE=""
SOURCE_SERVER=""
SOURCE_USER=""
SOURCE_PASSWORD=""
TARGET_SERVER=""
TARGET_USER=""
TARGET_PASSWORD=""
TAG_SUFFIX=""
LIST_OF_PLATFORM_IMAGES=""
LIST_OF_ARCHS=""
NR_OF_MANIFESTS=""
EXTRACT_PATH=""
CLEANUP=0
DEL_IMAGES=""
DEL_MANIFESTS=""
ARR_SI_TYPE=()
ARR_SI_PATH=()
ARR_SI_ARCH=()


function usage(){
  echo "Usage: pma2docker [options] <SOURCE_IMAGE> <TARGET_IMAGE>"
  echo " "
  echo "Options:"
  echo "  -a, --only-arch           - Split source multi-arch image and keep only specific arch (split multiple arch with comma: amd64,arm64)"
  echo "  -c, --cleanup             - Delete the specified and created docker images from your local disk."
  echo "  -s, --only-single-images  - Push only the single images with suffix, e.g. *-amd64, *-arm64, *-armv7"
  echo "      --source-user         - Username for Login at Source Repository"
  echo "      --source-password     - Password for Login at Source Repository"
  echo "      --target-user         - Username for Login at Target Repository"
  echo "      --target-password     - Password for Login at Target Repository"
  echo "      --suffix              - Append a suffix to the Target Tag"
  echo "      --log-level           - Set a log level: 0=FATAL,1=ERROR,2=WARNING,4=INFO,64=CUSTOM,128=VERBOSE - default: 71 (=0+1+2+4+64)"
  echo "      --log-mode            - Set the output format for log messages: 0=plain|1=simple|2=modern"
  echo " "
  echo " "
  echo "Usage: pma2docker [options] <SOURCE_IMAGE>"
  echo " "
  echo "Options:"
  echo "  -a, --only-arch           - Split source multi-arch image and keep only specific arch (split multiple arch with comma: amd64,arm64)"
  echo "  -c, --cleanup             - Delete the specified and created docker images from your local disk."
  echo "  -e, --extract             - Save Source Image to a file"
  echo "  -p, --pull-split          - Only download the image from Source Repository and add suffix without pushing it somewhere"
  echo "      --source-user         - Username for Login at Source Repository"
  echo "      --source-password     - Password for Login at Source Repository"
  echo "      --log-level           - Set a log level: 0=FATAL,1=ERROR,2=WARNING,4=INFO,64=CUSTOM,128=VERBOSE - default: 71 (=0+1+2+4+64)"
  echo "      --log-mode            - Set the output format for log messages: 0=plain|1=simple|2=modern"
  echo " "
  echo " "
  echo "Usage: pma2docker [options] <TARGET_IMAGE>"
  echo " "
  echo "Options:"
  echo "  -c, --cleanup             - Delete the specified and created docker images from your local disk."
  echo "  -m, --merge-push          - Load one or more single images you would like to combine to a multiarch image and push it. You can specify multiple single image references:"
  echo '                              Use this form: --merge-push "type=(oci|image),path=<(repository_path>|<path_to_tar.gz>),arch=<arch_of_single-image>"'
  echo "      --target-user         - Username for Login at Target Repository"
  echo "      --target-password     - Password for Login at Target Repository"
  echo "      --suffix              - Append a suffix to the Target Tag"
  echo "      --log-level           - Set a log level: 0=FATAL,1=ERROR,2=WARNING,4=INFO,64=CUSTOM,128=VERBOSE - default: 71 (=0+1+2+4+64)"
  echo "      --log-mode            - Set the output format for log messages: 0=plain|1=simple|2=modern"
  echo " "
  echo " "
  echo "Usage: pma2docker <version|help>"
  echo " "
  echo "List additional information abaout this tool"
  echo " "
}

function version(){
  logMe $LOG_VERBOSE "v.$VERSION  -- Maintainer: $MAINTAINER" "pma2docker"
}

function setPgmMode(){
  local requestedMode=$1

  # Callers can pass parameter which can be used by multiple modes of Normal- / Source- / Target- Mode. Passing a combination mode will not change the specified mode settings
  if [[ "$requestedMode" == $(("$NORMAL_MODE"+"$SOURCE_MODE")) ]] && [[ "$requestedMode" -ne "$TARGET_MODE" ]]; then
    if [[ $cnt -gt $(( "$PARM_CNT" - $NON_FLAG_CNT )) ]]; then
      PGM_MODE="$SOURCE_MODE"
      PGM_SETBY="$arg"
      NON_FLAG_CNT=1
      logMe $LOG_VERBOSE "Set Program Mode to 'Source Mode'"
    else
      PGM_MODE="$PGM_MODE"
      PGM_SETBY="$PGM_SETBY"
      NON_FLAG_CNT="$NON_FLAG_CNT"
    fi;
    return 0
  elif [[ "$requestedMode" == $(("$NORMAL_MODE"+"$TARGET_MODE")) ]] && [[ "$requestedMode" -ne "$SOURCE_MODE" ]]; then
    if [[ $cnt -gt $(( "$PARM_CNT" - $NON_FLAG_CNT )) ]]; then
      PGM_MODE="$TARGET_MODE"
      PGM_SETBY="$arg"
      NON_FLAG_CNT=1
      logMe $LOG_VERBOSE "Set Program Mode to 'Target Mode'"
    else
      PGM_MODE="$PGM_MODE"
      PGM_SETBY="$PGM_SETBY"
      NON_FLAG_CNT="$NON_FLAG_CNT"
    fi;
    return 0
  elif [[ "$requestedMode" == $(("$NORMAL_MODE"+"$SOURCE_MODE"+"$TARGET_MODE")) ]]; then
    PGM_MODE="$PGM_MODE"
    PGM_SETBY="$PGM_SETBY"
    NON_FLAG_CNT="$NON_FLAG_CNT"
    logMe $LOG_VERBOSE "Keep Program Mode to $PGM_MODE"
    return 0
  fi

  if [[ $PGM_MODE -ne $1 ]] && [[ $NOT_INITIALIZED_MODE -ne "-1" ]]; then
    logMe $LOG_ERROR "Invalid parameter combination. '""$arg""' is not compatible with '""$PGM_SETBY""'"
    exit 1
  fi
  if   [[ "$requestedMode" == "$INFO_MODE" ]]; then
    PGM_MODE="$INFO_MODE"
    PGM_SETBY="$arg"
    NON_FLAG_CNT=0
    logMe $LOG_VERBOSE "Set Program Mode to 'Info Mode'"
  elif [[ "$requestedMode" == "$NORMAL_MODE" ]]; then
    PGM_MODE="$NORMAL_MODE"
    PGM_SETBY="$arg"
    NON_FLAG_CNT=2
    logMe $LOG_VERBOSE "Set Program Mode to 'Normal Mode'"
  elif [[ "$requestedMode" == "$SOURCE_MODE" ]]; then
    PGM_MODE="$SOURCE_MODE"
    PGM_SETBY="$arg"
    NON_FLAG_CNT=1
    logMe $LOG_VERBOSE "Set Program Mode to 'Source Mode'"
  elif [[ "$requestedMode" == "$TARGET_MODE" ]]; then
    PGM_MODE="$TARGET_MODE"
    PGM_SETBY="$arg"
    NON_FLAG_CNT=1
    logMe $LOG_VERBOSE "Set Program Mode to 'Target Mode'"
  else
    logMe $LOG_ERROR "Illegal Mode selected by unknown problem. Abort..."
    exit 1
  fi
  return 0
}

function dependencyCheck(){
  logMe $LOG_INFO "Run dependency check..."
  # Check installed tools: bash, jq, docker
  bash --version > /dev/null 2>&1   || { logMe $LOG_ERROR "Dependency 'bash' is not installed. Please make sure that 'bash' ist installed and configured properly"; exit 1; }
  jq --version > /dev/null 2>&1     || { logMe $LOG_ERROR "Dependency 'jq' is not installed. Please make sure that 'jq' ist installed and configured properly"; exit 1; }
  docker --version > /dev/null 2>&1 || { logMe $LOG_ERROR "Dependency 'docker' is not installed. Please make sure that 'docker' ist installed and configured properly"; exit 1; }
  logMe $LOG_VERBOSE "Dependency Check for bash, jq, docker was successful!"

  # Check if command docker manifest is available
  [ $(docker manifest --help | grep "docker manifest COMMAND --help" | wc -l) -ge "1" ] || { logMe $LOG_ERROR "It loooks like there is noch command 'docker manifest' available on the system. Please verify, if you can run 'docker manifest --help' successfully on the system. You may need to enable docker's experimental client features!"; exit 1; }
  logMe $LOG_VERBOSE "Dependency Check for command 'docker manifest' was successful!"

  # Check if command docker buildx is available
  docker_server_start=$(docker info | grep -En "^Server" | cut -d':' -f1)
  client_plugins=$(docker info | head -n $(( $docker_server_start - 2)) | grep -A 100 'Plugins' | grep -v "Plugins" | awk '{ print; $1 }' | tr -d ' ' | cut -d':' -f1)
  logMe $LOG_VERBOSE "Got installed plugins for client: $(echo -n $client_plugins)"

  BUILDX_ENABLED="0"
  for plugin in $client_plugins
  do
    if [[ "$plugin" = "buildx" ]]; then
      BUILDX_ENABLED="1"
    fi
  done;

  if [[ "$BUILDX_ENABLED" = "0" ]]; then
    logMe $LOG_ERROR "Docker Plugin 'buildx' is needed to create multiarchitectural images. You can find neccessary information here: https://docs.docker.com/buildx/working-with-buildx/"
    exit 1
  else
    logMe $LOG_VERBOSE "Docker Plugin 'buildx' was found successfully."
  fi
}

function validateArch(){
  local IFS=$','
  local match="0"

  logMe $LOG_VERBOSE "Architecture list checking..."
  for a in $LIST_OF_ARCHS;
  do
    if [[ $a    == "linux/amd64"    ]]; then a="amd64"   ; fi;
    if [[ $a    == "linux/arm/v5"   ]]; then a="armv5"   ; fi;
    if [[ $a    == "linux/arm/v7"   ]]; then a="armv7"   ; fi;
    if [[ $a    == "linux/arm64/v8" ]]; then a="arm64"   ; fi;
    if [[ $a    == "linux/386"      ]]; then a="i386"    ; fi;
    if [[ $a    == "linux/mips64le" ]]; then a="mips64le"; fi;
    if [[ $a    == "linux/ppc64le"  ]]; then a="ppc64le" ; fi;
    if [[ $a    == "linux/riscv64"  ]]; then a="riscv64" ; fi;
    if [[ $a    == "linux/s390x"    ]]; then a="s390x"   ; fi;

    if [[ "$arch" == "$a" ]]; then match="1"; break; fi
  done

  if [[ "$match" == "1" ]]; then
    logMe $LOG_VERBOSE "Architecture matching default architecture list. Arch is $arch"
    return 0
  fi;
}

function validateAdjustImageTag(){
  ## Pre-Checks for Parameter
  if ( [[ $PGM_MODE == "$NORMAL_MODE" ]] || [[ $PGM_MODE == "$SOURCE_MODE" ]] ) && [[ $(basename $SOURCE_IMAGE | grep ":" | wc -l) -eq "0" ]]; then
    logMe $LOG_INFO "It looks like you did not specify a tag on source file. Asume 'latest' as tag."
    SOURCE_IMAGE="$SOURCE_IMAGE:latest"
  else
    logMe $LOG_VERBOSE "Source Image is fully qulified with tag: $SOURCE_IMAGE"
  fi

  if ( [[ $PGM_MODE == "$NORMAL_MODE" ]] || [[ $PGM_MODE == "$TARGET_MODE" ]] ) && [[ $(basename $TARGET_IMAGE | grep ":" | wc -l) -eq "0" ]]; then
    logMe $LOG_INFO "It looks like you did not specify a tag on target file. Asume 'latest' as tag."
    TARGET_IMAGE="$TARGET_IMAGE:latest"
  else
    logMe $LOG_VERBOSE "Target Image is fully qulified with tag: $TARGET_IMAGE"
  fi
}

function checkAndGetNrOfManifestsInManifestList(){
  # Check for Manifests in Image
  logMe $LOG_INFO "Run Inspect on Image $SOURCE_IMAGE"
  NR_OF_MANIFESTS=$(docker manifest inspect $SOURCE_IMAGE | jq '.manifests | length') > /dev/null 2>&1
  logMe $LOG_VERBOSE "Got $NR_OF_MANIFESTS manifests from image"
  if [[ $NR_OF_MANIFESTS -eq '0' ]]; then
    logMe $LOG_VERBOSE "Assume a single architecture image"
  fi


  re='^[0-9]+$'
  if ! [[ $NR_OF_MANIFESTS =~ $re ]] ; then
    logMe $LOG_ERROR "It looks like the Source Docker-Image is not suitable for this action.\nIt either does not exist or there was an error checking the provided Image."
    exit 1
  else
    logMe $LOG_VERBOSE "Docker Image Manifest for Source is valid, manifest contains $NR_OF_MANIFESTS images."
  fi
}


function checkImageIsDocker(){
  # Check if source images are Docker Images or Images from a custom repository
  docker_creds=$(cat ~/.docker/config.json | jq ".auths | keys" | grep -v "\[" | grep -v "\]" | tr -d ' ' | tr -d ',' | tr -d '"' | sed 's/https:\/\///g' | cut -d'/' -f1)

  logMe $LOG_VERBOSE "Checking Source and Target Images..."
  docker manifest inspect "docker.io/"$SOURCE_IMAGE > /dev/null 2>&1
  SOURCE_IS_DOCKER=$(test $? -eq 0 && echo "1" || echo "0")
  docker manifest inspect "docker.io/"$TARGET_IMAGE > /dev/null 2>&1
  TARGET_IS_DOCKER=$(test $? -eq 0 && echo "1" || echo "0")

  if [[ $SOURCE_IS_DOCKER = "1" ]] && [[ $(echo $SOURCE_IMAGE | grep "docker.io" | wc -l) == "0" ]]; then
    logMe $LOG_VERBOSE "Recognized Source Image as a image at docker hub. Add 'docker.io' as Prefix for Source Image"
    SOURCE_IMAGE="docker.io/"$SOURCE_IMAGE
  fi
  if [[ $TARGET_IS_DOCKER = "1" ]] && [[ $(echo $TARGET_IMAGE | grep "docker.io" | wc -l) == "0" ]]; then
    logMe $LOG_VERBOSE "Recognized Target Image as a image at docker hub. Add 'docker.io' as Prefix for Target Image"
    TARGET_IMAGE="docker.io/"$TARGET_IMAGE
  fi
  logMe $LOG_VERBOSE "Source-Image is $SOURCE_IMAGE"
  logMe $LOG_VERBOSE "Target-Image is $TARGET_IMAGE (may append arch tag or suffix later!)"
}


function checkExistingCredentials(){
  # Check if we do have credentials for source and target repository
  SOURCE_CREDS=0
  logMe $LOG_VERBOSE "Check Docker Credentials for the source repositories"
  for cred in $docker_creds;
  do
    if [[ $SOURCE_IMAGE  =~ .*$cred.* ]] || [[ $cred =~ .*docker\.io.* ]]; then
      logMe $LOG_INFO "Found entry for login credentials on Source Server, try to connect with them"
      SOURCE_CREDS=1
      break;
    fi
  done;

  TARGET_CREDS=0
  for cred in $docker_creds;
  do
    if [[ $TARGET_IMAGE =~ .*$cred.* ]] || [[ $SOURCE_IMAGE =~ .*docker\.io.* ]]; then
      logMe $LOG_INFO "Found entry for login credentials on Target Server, try to connect with them"
      TARGET_CREDS=1
      break;
    fi
  done;
}


function loginToRepositories(){
  # Validate checks for Repo-Images
  if [[ $SOURCE_CREDS == 0 ]]; then
    logMe $LOG_WARNING "There are no credentials to login to source repository, you may need to login to access the repo."
  fi
  if [[ $TARGET_CREDS == 0 ]]; then
    logMe $LOG_WARNING "There are no credentials to login to target repository, you may need to login to write to the repo."
  fi

  if [[ ! -z $SOURCE_USER ]]; then
    logMe $LOG_INFO "Try to login to Source repository with provided information..."
    if [[ -z $SOURCE_PASSWORD ]]; then
      logMe $LOG_INFO "Please enter password for Source Repository:"
      read -s -p "Please enter password for Source Repository:" SOURCE_PASSWORD
    fi
    SOURCE_SERVER=$(echo $SOURCE_IMAGE | cut -d'/' -f1)
    docker login $SOURCE_SERVER --username $SOURCE_USER --password $SOURCE_PASSWORD > /dev/null 2>&1
    if [[ ! $? -eq 0 ]]; then
      logMe $LOG_ERROR "Login to Source Repository was not successful to $SOURCE_SERVER, leaving..."
      exit 1
    else
      logMe $LOG_INFO "You may want to login with your credentials manually before passing user/password to this program to be sure, that your login works.\nYou do not need to specify credentials here, when you have already logged in with 'docker login'"
    fi
  fi;

  if [[ ! -z $TARGET_USER ]]; then
    logMe $LOG_INFO "Try to login to Target repository with provided information..."
    if [[ -z $TARGET_PASSWORD ]]; then
      logMe $LOG_INFO "Please enter password for Target Repository:"
      read -s -p "Please enter password for Target Repository:" TARGET_PASSWORD
    fi
    TARGET_SERVER=$(echo $TARGET_IMAGE | cut -d'/' -f1)
    docker login $TARGET_SERVER --username $TARGET_USER --password $TARGET_PASSWORD > /dev/null 2>&1
    if [[ ! $? -eq 0 ]]; then
      logMe $LOG_ERROR "Login to Target Repository was not successful TO $TARGET_SERVER, leaving..."
      exit 1
    else
      logMe $LOG_INFO "You may want to login with your credentials manually before passing user/password to this program to be sure, that your login works.\nYou do not need to specify credentials here, when you have already logged in with 'docker login'"
    fi
  fi;
}



function prepareSingleImage(){
   local isImage="0"
   local isOci="0"

   logMe $LOG_VERBOSE "Perparing Single-Image-Tags"
   if [[ $(echo $arg | grep -E "^type=image,path=.*,arch=.*$" | wc -l) -eq "1" ]]; then isImage="1"; fi
   if [[ $(echo $arg | grep -E "^type=oci,name=.*,path=.*,arch=.*$" | wc -l) -eq "1" ]]; then isOci="1"; fi

   if [[ "$isImage" == "0" ]] && [[ "$isOci" == "0" ]]; then
     logMe $LOG_ERROR 'Specified single image definition is not valid. Please enter a specification string to address image in this form:\n     --merge-push "type=(oci|image),path=<(repository_path>|<path_to_tar.gz>),arch=<arch_of_single-image>"\n\n Example: pma2docker --merge-push "type=image,dobernoeder/helloworld:latest,arch=amd64" dobernoeder/newworld:latest-amd64\n'
     exit 1
   else
     logMe $LOG_VERBOSE "Found a valid image specification string: $arg"
   fi

   if [[ "$isImage" -eq "1" ]]; then
     ARR_SI_TYPE+=("$(echo $arg | cut -d',' -f1 | cut -d'=' -f2 )")
     ARR_SI_NAME+=("$(echo $arg | cut -d',' -f2 | cut -d'=' -f2 )")
     ARR_SI_PATH+=("$(echo $arg | cut -d',' -f2 | cut -d'=' -f2 )")
     ARR_SI_ARCH+=("$(echo $arg | cut -d',' -f3 | cut -d'=' -f2 )")
     logMe $LOG_VERBOSE "Recognized input specification for image type"
   fi;

   if [[ "$isOci" -eq "1" ]]; then
     ARR_SI_TYPE+=("$(echo $arg | cut -d',' -f1 | cut -d'=' -f2 )")
     ARR_SI_NAME+=("$(echo $arg | cut -d',' -f2 | cut -d'=' -f2 )")
     ARR_SI_PATH+=("$(echo $arg | cut -d',' -f3 | cut -d'=' -f2 )")
     ARR_SI_ARCH+=("$(echo $arg | cut -d',' -f4 | cut -d'=' -f2 )")
     logMe $LOG_VERBOSE "Recognized input specification for OCI type"
   fi;
}

function tagImage(){
   local srcTag="$1"
   local destTag="$2"

   docker tag "$srcTag" "$destTag"
   if [[ $? -eq 0 ]]; then
     logMe $LOG_INFO "Tagged Image from $srcTag to $destTag"
     DEL_IMAGES="$DEL_IMAGES"" ""$2"
   else
     logMe $LOG_ERROR "Unable to tag new image for architecture $arch. Abort process..."
    exit 1
   fi
}

function checkImportFile(){
  local importFile=$1

  # Check if extract path exists when --extract was set
  if [ ! -d $importFile ]; then
    logMe $LOG_ERROR "You specified an image file for import. The Image does not exist. You must specify an valid, existing directory as a *.tar.gz which is compliant to oci specification."
    exit 1
  fi
}

function importImage(){
  logMe $LOG_INFO "Load Image $1 from $2"
  docker import "$2" "$1"
  if [[ ! $? -eq 0 ]]; then logMe $LOG_ERROR "Was not able to import image $1 from file $2. Please make sure, that the import file is a *.tar.gz valid to the oci specification."; exit 1; fi;
}

function pullImage(){
  logMe $LOG_INFO "Pulling Image $1 ..."
  docker pull "$1"
  if [[ ! $? -eq 0 ]]; then logMe $LOG_ERROR "Unable to pull image for architecture $arch. Abort process..."; exit 1; fi
  DEL_IMAGES="$DEL_IMAGES"" ""$1"
}

function pushImage(){
  logMe $LOG_INFO "Pushing Image $1 to target repository ..."
  docker push "$1"
  if [[ ! $? -eq 0 ]]; then logMe $LOG_ERROR "Unable to push $1. Abort process..."; exit 1; fi
}

function pushManifest(){
  logMe $LOG_INFO "Pushing Manifest $1 to target repository ..."
  docker manifest push "$1"
  if [[ ! $? -eq 0 ]]; then logMe $LOG_ERROR "Unable to push Manifest for $1. Abort process..."; exit 1; fi
}

function saveImage(){
  logMe $LOG_INFO "Saving image file to $EXTRACT_PATH/image-$arch.tar.gz ..."
  docker save -o $EXTRACT_PATH"/image-$arch.tar.gz" "$1"
}

function getHostArch(){
architecture=""
  case $(uname -m) in
      s390x)   architecture="s390x" ;;
      x86_64)  architecture="amd64" ;;
      arm64)   architecture="arm64" ;;
  esac
}

function createMultiArchImage(){
  local image="$1"
  local platforms="$2"
  local checkImage=""

  logMe $LOG_VERBOSE "Run inspect on Image $image"
  #checkImage=$(docker manifest inspect $image | jq '.manifests | length') > /dev/null 2>&1
  check=$(docker manifest inspect "$image")
  echo ">>> DEBUG1"
  if [ $? -eq "0" ]; then
    docker manifest rm "$image"  2>/dev/null
  fi
  echo ">>> DEBUG2"
  logMe $LOG_VERBOSE "Create manifest for Image $image and Plattform $platform"
  echo ">>> DEBUG3"
  docker manifest create $image $platforms
  if [[ ! $? -eq 0 ]]; then logMe $LOG_ERROR "Unable to create manifest for multi-arch image. Abort process..."; exit 1; fi
  DEL_MANIFESTS="$DEL_MANIFESTS"" ""$1"
}

#function analyzeSourceManifest(){
#  # Get Information for Manifest
#  if [[ "$NR_OF_MANIFESTS" -eq "0" ]]; then
#    manifest=$(docker manifest inspect $SOURCE_IMAGE | jq '.manifests'["${c}"])
#  else
#   manifest=$(docker manifest inspect dobernoeder/helloworld  | jq '.layers[0]')
#  fi
#  digest=$(echo $manifest | jq -r '.digest')
#  arch=$(echo $manifest | jq -r '.platform.architecture')
#  logMe $LOG_VERBOSE "Analysed Source Image Manifest with $arch and fingerprint $digest"
#
#  # Check if we have a variant for an architecture, for example arm/v7
#  if [[ $(echo $manifest | jq -r '.platform.variant') != "null" ]]; then
#    arch="$arch"$(echo $manifest | jq -r '.platform.variant')
#  fi
#}

function analyzeSourceManifest(){
  # Get Information for Manifest
  if [[ "$NR_OF_MANIFESTS" -eq "0" ]]; then
    manifest=$(docker manifest inspect $SOURCE_IMAGE | jq '.manifests'["${c}"])
    getHostArch
    arch="$architecture"
  else
    manifest=$(docker manifest inspect dobernoeder/helloworld  | jq '.layers[0]')
    arch=$(echo $manifest | jq -r '.platform.architecture')
    # Check if we have a variant for an architecture, for example arm/v7
    if [[ $(echo $manifest | jq -r '.platform.variant') != "null" ]]; then
      arch="$arch"$(echo $manifest | jq -r '.platform.variant')
    fi
  fi
  digest=$(echo $manifest | jq -r '.digest')
  logMe $LOG_VERBOSE "Analysed Source Image Manifest with $arch and fingerprint $digest"
}


function getSingleImages(){

  for (( i=0; i<${#ARR_SI_PATH[@]}; i++ ));
  do
    if [[ ${ARR_SI_TYPE[$i]} == "image" ]]; then
      pullImage "${ARR_SI_PATH[$i]}"
    elif [[ ${ARR_SI_TYPE[$i]} == "oci" ]]; then
      importImage "${ARR_SI_NAME[$i]}" "${ARR_SI_PATH[$i]}"
    else
     logMe $LOG_FATAL "Internal process error due to invalid type specification for single image no. $i"
     exit 1
    fi
    LIST_OF_PLATFORM_IMAGES="$LIST_OF_PLATFORM_IMAGES"" "${ARR_SI_PATH[$i]}
  done
  logMe $LOG_VERBOSE "Recognized the following list of single images: $LIST_OF_PLATFORM_IMAGES"
}

function copyMultiArchToLocal(){
  # If NR_OF_IMAGES is zero, no multiarch image, so assume local arch and set it to one
  if [[ $NR_OF_MANIFESTS -eq "0" ]]; then
    #getHostArch
    LIST_OF_PLATFORM_IMAGES="$architecture"
    NR_OF_MANIFESTS=1
  fi
  # Cycle through all Manifests in the manifest of the Manifest-List
  for (( c=0; c<$NR_OF_MANIFESTS; c++ ));
  do
    analyzeSourceManifest
    PLATFORM_TARGET_IMAGE="$TARGET_IMAGE""-""$arch""-""$TAG_SUFFIX"
    if [ ! -z "$arch" ] && [ ! -z "$digest" ] && ( validateArch || [ -z "$LIST_OF_ARCHS" ] ); then
      logMe $LOG_INFO " $arch ---------------------------------------------------------------------------------------"
      pullImage "$SOURCE_IMAGE""@""$digest"
      tagImage  "$SOURCE_IMAGE""@""$digest" "$PLATFORM_TARGET_IMAGE"
      if [[ $ONLY_PULL_SPLIT == "0" ]] && [[ -z $EXTRACT_PATH ]]; then
        pushImage "$PLATFORM_TARGET_IMAGE"
      fi
      if [[ ! -z $EXTRACT_PATH ]]; then
        logMe $LOG_INFO "Saving image file to $EXTRACT_PATH/image-$arch.tar.gz ..."
        saveImage "$PLATFORM_TARGET_IMAGE"
      fi;
      LIST_OF_PLATFORM_IMAGES="$LIST_OF_PLATFORM_IMAGES"" ""$PLATFORM_TARGET_IMAGE"
    fi;

    # Reset values for $arch and $digest
    arch=""
    digest=""
  done;
}

function multiArchUpload(){
  # Check for existing manifest and delete it before creating new one, if Multi-Arch-Push is not deactivated
  logMe $LOG_INFO " MULTI-ARCH Creation & Upload --------------------------------------------------------------------"
   echo ">>> DEBUG: oSI = $ONLY_SINGLE_IMAGES  -- oPS = $ONLY_PULL_SPLIT"
  if [[ "$ONLY_SINGLE_IMAGES" -eq "0" ]] && [[ "$ONLY_PULL_SPLIT" -eq "0" ]]; then
    createMultiArchImage "$TARGET_IMAGE" "$LIST_OF_PLATFORM_IMAGES"
    if [[ -z $EXTRACT_PATH ]]; then
      pushManifest "$TARGET_IMAGE" "'""$LIST_OF_PLATFORM_IMAGES""'"
    fi;
  else
    logMe $LOG_WARNING ">>> SKIP Multi-Architecture Creation & Upload due to Parameter --only-single-images or --pull-split is set"
    if [[ ! -z $EXTRACT_PATH ]]; then
      logMe $LOG_WARNING "Export of multi architecture images to files is currently not supported. The option --only-single-images is activated automatically when setting --extract parameter!"
    fi
  fi;
}

function cleanup(){
  logMe $LOG_INFO "Delete Manifests..."
  docker manifest rm $DEL_MANIFESTS 2>/dev/null
  logMe $LOG_INFO "Delete Images..."
  if [[ ! -z "$DEL_IMAGES" ]]; then
    docker image rm $DEL_IMAGES
  fi
}

## START OF PROCESS ##
version
dependencyCheck

# Parameter handling
cnt=0
for arg in "$@"; do
  cnt=$(( $cnt+1 ))
  if [[ "$arg" == "--version" ]];                 then setPgmMode $INFO_MODE;                     version; exit; fi;
  if [[ "$arg" == "--help" ]];                    then setPgmMode $INFO_MODE;                     usage;   exit; fi;
  if [[ "$arg" == "--source-user" ]];             then setPgmMode $(($NORMAL_MODE+$SOURCE_MODE)); NEXT_ITEM="--source-user"; continue; fi;
  if [[ "$arg" == "--source-password" ]];         then setPgmMode $(($NORMAL_MODE+$SOURCE_MODE)); NEXT_ITEM="--source-password"; continue; fi;
  if [[ "$arg" == "--target-user" ]];             then setPgmMode $(($NORMAL_MODE+$TARGET_MODE)); NEXT_ITEM="--target-user"; continue; fi;
  if [[ "$arg" == "--target-password" ]];         then setPgmMode $(($NORMAL_MODE+$TARGET_MODE)); NEXT_ITEM="--target-password"; continue; fi;
  if [[ "$arg" == "--pull-split" ]] \
  || [[ "$arg" == "-p" ]];                        then setPgmMode $SOURCE_MODE; ONLY_PULL_SPLIT=1; continue; fi;
  if [[ "$arg" == "--only-single-images" ]] \
  || [[ "$arg" == "-s" ]];                        then setPgmMode $(($NORMAL_MODE+$TARGET_MODE)); ONLY_SINGLE_IMAGES=1; continue; fi;
  if [[ "$arg" == "--only-arch" ]] \
  || [[ "$arg" == "-a" ]];                        then setPgmMode $(($NORMAL_MODE+$SOURCE_MODE)); NEXT_ITEM="--only-arch"; continue; fi;
  if [[ "$arg" == "--extract" ]] \
  || [[ "$arg" == "-e" ]];                        then setPgmMode $SOURCE_MODE; NEXT_ITEM="--extract"; continue; fi;
  if [[ "$arg" == "--merge-push" ]] \
  || [[ "$arg" == "-m" ]];                        then setPgmMode $TARGET_MODE; NEXT_ITEM="--merge-push"; continue; fi;
  if [[ "$arg" == "--cleanup" ]] \
  || [[ "$arg" == "-c" ]];                        then setPgmMode $(($NORMAL_MODE+$SOURCE_MODE+$TARGET_MODE)); CLEANUP=1; continue; fi;
  if [[ "$arg" == "--suffix" ]];                  then setPgmMode $(($NORMAL_MODE+$SOURCE_MDOE+$TARGET_MODE)); NEXT_ITEM="--suffix"; continue; fi;
  if [[ "$arg" == "--log-level" ]];               then setPgmMode $(($NORMAL_MODE+$SOURCE_MODE+$TARGET_MODE)); NEXT_ITEM="--log-level"; continue; fi;
  if [[ "$arg" == "--log-mode" ]];               then setPgmMode $(($NORMAL_MODE+$SOURCE_MODE+$TARGET_MODE)); NEXT_ITEM="--log-mode"; continue; fi;
  if [[ $cnt -le $(( "$PARM_CNT" - $NON_FLAG_CNT )) ]]; then
    if [[ "$NEXT_ITEM" == "--log-level" ]];         then setLogLevel "$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--log-mode" ]];          then setLogMode "$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--suffix" ]];            then TAG_SUFFIX="$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--source-user" ]];       then SOURCE_USER="$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--source-password" ]];   then SOURCE_PASSWORD="$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--target-user" ]];       then TARGET_USER="$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--target-password" ]];   then TARGET_PASSWORD="$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--only-arch" ]];         then LIST_OF_ARCHS="$arg"; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--extract" ]];           then EXTRACT_PATH="$arg"; ONLY_SINGLE_IMAGES=1; NEXT_ITEM=""; continue; fi
    if [[ "$NEXT_ITEM" == "--merge-push" ]];        then prepareSingleImage; NEXT_ITEM=""; continue; fi
  fi
  if [[ "$PGM_MODE" == "$NOT_INITIALIZED_MODE" ]]; then PGM_MODE=$NORMAL_MODE; fi;  # If not initialized by Flag-Parameter, set to Normal mode
  if [[ "$PGM_MODE" == "$NORMAL_MODE" ]]; then
    if [[ "$cnt" == $(( "$PARM_CNT" -1 )) ]];              then SOURCE_IMAGE="$arg"; continue; fi;
    if [[ "$cnt" == $(( "$PARM_CNT" -0 )) ]];              then TARGET_IMAGE="$arg"; continue; fi;
  fi
  if [[ "$PGM_MODE" == "$TARGET_MODE" ]]; then
    if [[ "$cnt" == $(( "$PARM_CNT" -0 )) ]];              then TARGET_IMAGE="$arg"; continue; fi;
  fi
  if [[ "$PGM_MODE" == "$SOURCE_MODE" ]]; then
    if [[ "$cnt" == $(( "$PARM_CNT" -0 )) ]];              then SOURCE_IMAGE="$arg"; continue; fi;
  fi
  logMe $LOG_ERROR "Unknown parameter: $arg"
  usage
  exit 1
done

if [[ "$PGM_MODE" = "$TARGET_MODE" ]]; then
  logMe $LOG_VERBOSE "Entering Target Image mode"
  checkImageIsDocker
  getSingleImages
  tagImage ${ARR_SI_PATH[0]} $TARGET_IMAGE
  pushImage $TARGET_IMAGE
  createMultiArchImage $TARGET_IMAGE "$LIST_OF_PLATFORM_IMAGES"
  pushManifest $TARGET_IMAGE
  if [[ $CLEANUP == "1" ]]; then
    logMe $LOG_VERBOSE "Cleanup got triggered delete images $DEL_IMAGES"
    logMe $LOG_VERBOSE "Cleanup got triggered delete manifests $DEL_MANIFESTS"
    cleanup
  fi
  exit 0
fi

if [[ "$PGM_MODE" = "$NORMAL_MODE" ]]; then
  logMe $LOG_VERBOSE "Entering normal mode"
  validateAdjustImageTag
  checkAndGetNrOfManifestsInManifestList
  checkImageIsDocker
  checkExistingCredentials
  loginToRepositories
  copyMultiArchToLocal
  multiArchUpload
  if [[ $CLEANUP == "1" ]]; then
    logMe $LOG_VERBOSE "Cleanup got triggered delete images $DEL_IMAGES"
    logMe $LOG_VERBOSE "Cleanup got triggered delete manifests $DEL_MANIFESTS"
    cleanup
  fi
  exit 0
fi

# Additional parameter inspection and handling
if [[ "$PGM_MODE" = "$SOURCE_MODE" ]]; then
  TARGET_IMAGE="$SOURCE_IMAGE"
  if [[ $ONLY_PULL_SPLIT == "1" ]] || [[ ! -z $EXTRACT_PATH ]]; then
    if [ ! -z $TARGET_USER ] || [ ! -z $TARGET_PASSWORD ]; then
      logMe $LOG_WARNING " --target-user and --target-password are not applicable with --pull-split and will be ignored!"
      TARGET_USER=""
      TARGET_PASSWORD=""
    fi
  fi;

  # Check if extract path exists when --extract was set
  if [ ! -d $EXTRACT_PATH ]; then
    logMe $LOG_ERROR "You specified the --extract option to save an image to a file. You must specify an valid, existing directory to export the *.tar.gz"
    exit 1
  fi

  validateAdjustImageTag
  checkAndGetNrOfManifestsInManifestList
  checkImageIsDocker
  checkExistingCredentials
  loginToRepositories
  copyMultiArchToLocal
  if [[ $CLEANUP == "1" ]]; then
    logMe $LOG_VERBOSE "Cleanup got triggered delete images $DEL_IMAGES"
    logMe $LOG_VERBOSE "Cleanup got triggered delete manifests $DEL_MANIFESTS"
    cleanup
  fi
  exit 0

fi

# if only one paramter was added, this cannot run properly, prompt usage dialog and end
if [[ -z $SOURCE_IMAGE ]] || [[ -z $TARGET_IMAGE ]]; then
  logMe $LOG_ERROR "Invalid parameter combination"
  usage
  exit 1
fi
